<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>DualBlade._3D.Rendering</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DualBlade.Analyzer\DualBlade.Analyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\DualBlade.Core\DualBlade.Core.csproj"/>
        <PackageReference Include="Jab" Version="0.10.2"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.2.1105"/>
    </ItemGroup>

</Project>
